webtalk_init -webtalk_dir C:/Users/yashp/OneDrive/Documents/riscv_verification/single_stage_processor/single_stage_procesor.sim/sim_1/behav/xsim/xsim.dir/tb_control_unit_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Oct 13 00:19:46 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e38a5bc2-a64a-4bc9-afb6-3895aef8b392" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "375da1d1fab2419e825b65a64720ee47" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "46" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-1235U" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "42.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "70 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8464_KB" -context "xsim\\usage"
webtalk_transmit -clientid 54607129 -regid "" -xml C:/Users/yashp/OneDrive/Documents/riscv_verification/single_stage_processor/single_stage_procesor.sim/sim_1/behav/xsim/xsim.dir/tb_control_unit_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/yashp/OneDrive/Documents/riscv_verification/single_stage_processor/single_stage_procesor.sim/sim_1/behav/xsim/xsim.dir/tb_control_unit_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/yashp/OneDrive/Documents/riscv_verification/single_stage_processor/single_stage_procesor.sim/sim_1/behav/xsim/xsim.dir/tb_control_unit_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
